theme = "ayu_dark"

[editor]
line-number = "relative"

[editor.lsp]
display-inlay-hints = true

[editor.cursor-shape]
insert = "underline"

[keys.normal."backspace"]
c = ":bc"
C = [":w", ":bc"]
w = ":w"
W = ":wa"
x = ":xa"
f = ":format"
