[language-server.lemminx]
command = "lemminx"

[language-server.rust-analyzer.config.check]
command = "clippy"

[[language]]
name = "rust"
auto-format = true

[[language]]
name = "toml"
formatter = { command = "taplo", args = ["format", "-"] }

[[languge]]
name = "python"
formatter = { command = "black", args = ["--quiet", "-"] }
auto-format = true

[[language]]
name = "java"
file-types = ["java", "pde"]
formatter = { command = "google_java_format" }
# auto-format = true

[[language]]
name = "bash"
indent = { tab-width = 4, unit = "\t" }
formatter = { command = "shfmt" }
auto-format = true

[[language]]
name = "fish"
formatter = { command = "fish_indent" }
auto-format = true

[[language]]
name = "javascript"
formatter = { command = 'prettier', args = ["--parser", "javascript"] }
auto-format = true

[[language]]
name = "json"
formatter = { command = 'deno', args = ["fmt", "-", "--ext", "json"] }

[[language]]
name = "typescript"
#formatter = { command = 'deno', args = ["fmt", "-", "--ext", "ts"] }
formatter = { command = 'prettier', args = ["--parser", "typescript"] }
auto-format = true

[[language]]
name = "markdown"
formatter = { command = 'prettier', args = ["--parser", "markdown"] }
auto-format = true

[[language]]
name = "xml"
file-types = ["xml", "ui"]
language-servers = ["lemminx"]
formatter = { command = "xmllint", args = ["--format"] }
