# auto-format = true

[[language]]
name = "rust"
auto-format = true

[[toml]]
name = "toml"
formatter = { command = "taplo", args = ["format", "-"] }

[language.config.checkOnSave]
command = "clippy"

[[languge]]
name = "python"
formatter = { command = "black", args = ["--quiet", "-"] }
auto-format = true

[[language]]
name = "java"
file-types = ["java", "pde"]

[[language]]
name = "bash"
indent = { tab-width = 4, unit = "\t" }
formatter = { command = "shfmt" }
auto-format = true

[[language]]
name = "fish"
formatter = { command = "fish_indent" }
auto-format = true

[[language]]
name = "javascript"
formatter = { command = 'deno', args = ["fmt", "-", "--ext", "js" ] }
auto-format = true

[[language]]
name = "json"
formatter = { command = 'deno', args = ["fmt", "-", "--ext", "json" ] }

[[language]]
name = "markdown"
formatter = { command = 'deno', args = ["fmt", "-", "--ext", "md" ] }
auto-format = true

[[language]]
name = "typescript"
formatter = { command = 'deno', args = ["fmt", "-", "--ext", "ts" ] }
auto-format = true

[[language]]
name = "jsx"
formatter = { command = 'deno', args = ["fmt", "-", "--ext", "jsx" ] }
auto-format = true

[[language]]
name = "tsx"
formatter = { command = 'deno', args = ["fmt", "-", "--ext", "tsx" ] }
auto-format = true

[[language]]
name = "xml"
file-types=["xml","ui"]
language-server = {command = "lemminx"}
formatter = {command = "xmllint", args = ["--format"]}