env = XDG_MENU_PREFIX,plasma-

# Userspace tools
# exec-once = kwalletd6
exec-once = uwsm app -- /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
exec-once = uwsm app -- gnome-keyring-daemon --start --components=secrets
exec-once = uwsm app -- hypridle
exec-once = uwsm app -- elephant
exec-once = uwsm app -- wpaperd 
exec-once = uwsm app -- nextcloud
exec-once = LC_TIME=de_DE.utf8 uwsm app -- ironbar

# Execute your favorite apps at launch
exec-once = uwsm app -- bitwarden-desktop
exec-once = uwsm app -- kdeconnect-indicator
