windowrule {
	name = waybar
	match:class = waybar
	float = on
}
windowrule {
	name = keepassxc
	match:class = org.keepassxc.KeePassXC
	float = on
}
windowrule {
	name = nm-tray
	match:class = nm-tray
	float = on
}
windowrule {
	name = PIP
	match:title = Picture-in-Picture
	float = on
	keep_aspect_ratio = on
}
windowrule {
	name = SCB_Playtest
	match:title = SCB_Playtest
	float = on
}
windowrule {
	name = SCB
	match:title = SCB
	float = on
}
windowrule {
	name = SCB_Demo
	match:title = SCB_Demo
	float = on
}
