position = "top"
height = 8

[[start]]
type = "workspaces"

[[start]]
type = "focused"
icon_size = 20

[[start]]
type = "launcher"
icon_size = 20

[[start]]
type = "music"

[[center]]
type = "sys_info"
#" {cpu_percent}%  {temp_c:coretemp-isa-0000}°C",
format = [
  " {cpu_percent}%",
  "󰚗 {memory_percent}%",
  " {uptime}"
]

[center.interval]
memory = 15
cpu = 1
temps = 2

[[end]]
type = "tray"
direction = "left_to_right"

[[end]]
type = "clipboard"

[[end]]
type = "notifications"

[[end]]
type = "upower"
format = "{percentage}% ~ {time_remaining}"

[[end]]
type = "clock"
format = "%d/%m/%Y %H:%M:%S"
