name = "topbar"
position = "top"
height = 4

[[start]]
type = "workspaces"

[[start]]
type = "focused"
icon_size = 20

[start.truncate] 
mode = "middle"
max_length = 35

[[start]]
type = "music"

[start.truncate] 
mode = "middle"
max_length = 20

[[start]]
type = "launcher"
icon_size = 20

[[center]]
type = "sys_info"
#" {cpu_percent}%  {temp_c:coretemp-isa-0000}°C",
format = [
  "   {cpu_percent}% : {cpu_frequency}",
  "󰚗  {memory_percent}%",
  " {net_down:wlan0}/{net_up:wlan0} 󰁅",
  "   {uptime}",
]

[center.interval]
memory = 15
cpu = 1
temps = 2
network = 1

[[end]]
type = "label"
label = "#idlemsg"

[[end]]
type = "tray"

[[end]]
type = "clipboard"

[[end]]
type = "notifications"

[[end]]
type = "upower"
# Only show if not on desktop
show_if = "if  [[ $(cat /sys/class/dmi/id/chassis_type) -eq 3 ]]; then false; else true; fi"
format = "{percentage}% ~ {time_remaining}"

[[end]]
type = "clock"
locale = "de_DE"
format = "%d.%m.%Y %H:%M:%S"
