position = "top"
name = "topbar"
height = 4

[[start]]
type = "workspaces"

[[start]]
type = "focused"
icon_size = 20

[start.truncate] 
mode = "middle"
max_length = 35

[[start]]
type = "music"

[start.truncate] 
mode = "middle"
max_length = 20

[[start]]
type = "launcher"
icon_size = 20

[[center]]
type = "sys_info"
#" {cpu_percent}%  {temp_c:coretemp-isa-0000}°C",
format = [
  " {cpu_percent}%",
  "󰚗 {memory_percent}%",
  " {uptime}"
]

[center.interval]
memory = 15
cpu = 1
temps = 2

[[end]]
type = "tray"
direction = "left_to_right"

[[end]]
type = "clipboard"

[[end]]
type = "notifications"

[[end]]
type = "upower"
# Only show if not on desktop
show_if = "if grep -q 3 /sys/class/dmi/id/chassis_type; then exit 1; else exit 0; fi"
format = "{percentage}% ~ {time_remaining}"

[[end]]
type = "clock"
format = "%d.%m.%Y %H:%M:%S"
