[language-server]
lemminx = { command = "lemminx" }
arduino-lsp = { command = "arduino-language-server" }
htmx-lsp = { command = "htmx-lsp2" }

[language-server.rust-analyzer.config.check]
command = "clippy"

[language-server.pylsp.config.pylsp.plugins]
flake8 = {enabled = true}
pylint = {enabled = false}
ruff = {enabled = false}

[[language]]
name = "rust"
auto-format = true

[[language]]
name = "toml"
formatter = { command = "taplo", args = ["format", "-"] }

[[languge]]
name = "python"
formatter = { command = "autopep8" }

[[language]]
name = "java"
file-types = ["java", "pde"]
formatter = { command = "google_java_format" }
# auto-format = true

[[language]]
name = "bash"
indent = { tab-width = 4, unit = "\t" }
formatter = { command = "shfmt" }
auto-format = true

[[language]]
name = "javascript"
formatter = { command = 'prettier', args = ["--parser", "javascript"] }
auto-format = true

[[language]]
name = "json"
formatter = { command = 'deno', args = ["fmt", "-", "--ext", "json"] }

[[language]]
name = "typescript"
#formatter = { command = 'deno', args = ["fmt", "-", "--ext", "ts"] }
formatter = { command = 'prettier', args = ["--parser", "typescript"] }
auto-format = true

[[language]]
name = "markdown"
formatter = { command = 'prettier', args = ["--parser", "markdown"] }
#auto-format = true

[[language]]
name = "xml"
file-types = ["xml", "ui"]
language-servers = ["lemminx"]
formatter = { command = "xmllint", args = ["--format"] }

[[language]]
name = "html"
language-servers = [ "vscode-html-language-server", "htmx-lsp" ]

[[language]]
name = "arduino"
scope = "source.arduino"
injection-regex = "arduino"
file-types = ["ino", "cpp", "h"]               # ⭐ this line is what matters
comment-token = "//"
roots = ["sketch.yaml"]
language-servers = ["arduino-lsp"]
indent = { tab-width = 4, unit = "    " }
auto-format = true
formatter = { command = "clang-format" }
